apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-p7qg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-p7qg
    app.kubernetes.io/part-of: tkrw-pr712-0075-0069-app
  name: devfile-sample-p7qg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-p7qg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-p7qg
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0069-tenant/tkrw-pr712-0075-0069-app/devfile-sample-p7qg@sha256:1890239613389e4f6feb10b760081327b4752f67026dee4dc18b0eeef7699afb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
